title: Swapnil Shrikhande
description: > # this means to ignore newlines until "baseurl:"
  This is my personal blog. 
  I love to explore algorithms and innovative ways to design efficient systems.
  Algorithms, Salesforce, Design Patterns, Open Source are some of my interest areas. 
permalink: '/:categories/:title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://swapnilshrikhande.in" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Swapnil Shrikhande # add your name
author-img: swapnil-shrikhande.jpg # add your photo
about-author: designeener who likes to solve problems and then write the code # add description
twitter: svshrikhande # add your Twitter handle
facebook: shrikhande.swapnil # add your Facebook handle
github: swapnilshrikhande # add your Github handle
linkedin: swapnilshrikhande # add your Linkedin handle
email: swapnilshrikhande.in@gmail.com # add your Email address
instagram: shrikhande.swapnil

# Disqus
discus-identifier: swapnilshrikhande-in # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
include: [".well-known"]
